sudo: false
language: c
os:
- linux
env: 
  matrix:
  - VERSION=1
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - bsdtar
    - doxygen
script:
- make hello
after_success: 
- ./publish.sh
