sudo: false
language: c
os:
- linux
env: 
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - bsdtar
    - doxygen
install: 
script:
- make hello
- ./publish.sh
before_install:
- ls ~/.ssh/
- openssl aes-256-cbc -K $encrypted_3b52e9352b1f_key -iv $encrypted_3b52e9352b1f_iv
  -in travisci_rsa.enc -out travisci_rsa -d
- chmod 0600 travisci_rsa
- cp travisci_rsa ~/.ssh/id_rsa
after_sucess: 
