sudo: false
language: c
os:
- linux
env:
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - bsdtar
    - doxygen
install:
script:
- make hello
before_install:
- openssl aes-256-cbc
  -K $encrypted_dc9ab2986818_key
  -iv $encrypted_dc9ab2986818_iv
  -in  travisci_rsa.enc
  -out travisci_rsa
  -d
after_sucess: 
- publish.sh
