sudo: false
language: c
os:
- linux
env: 
  global:
  - CORE_REPO=0
  matrix:
  - VERSION=1
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - bsdtar
    - doxygen
install: 
script:
- make hello
after_success: 
- ./publish.sh
