sudo: false
language: c
os:
- linux
env:
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - bsdtar
    - doxygen
install:
script:
- make hello
before_install:
after_sucess: 
- publish.sh
